using System.Numerics;
using Content.Client.Shuttles.UI;
using Content.Shared.Imperial.Medieval.CartographerTable;
using Content.Shared.Imperial.Medieval.MedievalMap;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Collections;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics;
using Robust.Shared.Physics.Components;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.CartographerTable;


[GenerateTypedNameReferences]
public sealed partial class MedievalCartographerTableNavControl : BaseShuttleControl
{
    private const float SilhouetteAlpha = 0.28f;

    [Dependency] private readonly IMapManager _mapManager = default!;
    [Dependency] private readonly ITileDefinitionManager _tileDefinitions = default!;

    private readonly SharedShuttleSystem _shuttles;
    private readonly SharedTransformSystem _transform;
    private List<Entity<MapGridComponent>> _grids = new();
    private Vector2[] _silhouetteVertices = Array.Empty<Vector2>();
    private readonly Dictionary<EntityUid, GeographyDrawData> _geographyData = new();
    private readonly Dictionary<int, Color> _terrainColors = new();

    private sealed class GeographyDrawData
    {
        public GameTick? LastBuild;
        public readonly Dictionary<Color, List<Vector2>> Vertices = new();
    }

    private EntityCoordinates? _coordinates;
    private Angle? _rotation;
    private bool _rotateWithEntity = true;

    private List<CartographerRadarMarkerData> _radarMarkers = new();
    [Dependency] private readonly IResourceCache _resCache = default!;

    /// <summary>Use the table's geography display for a handheld map without its live radar markers.</summary>
    public bool FieldNotesMode;
    public List<MedievalMapAnnotation> Annotations = new();
    public int? DisplayedWorldMap;
    public int SelectedAnnotation = -1;
    public Action<int>? OnSelectAnnotation;
    protected override bool Draggable => FieldNotesMode;

    public MedievalCartographerTableNavControl() : base(32f, 256f, 256f)
    {
        RobustXamlLoader.Load(this);
        _shuttles = EntManager.System<SharedShuttleSystem>();
        _transform = EntManager.System<SharedTransformSystem>();
    }

    public void UpdateState(MedievalCartographerBoundUserInterfaceState state)
    {
        var coordinates = EntManager.GetCoordinates(state.Coordinates);
        if (FieldNotesMode && (_coordinates == null || _coordinates.Value.EntityId != coordinates.EntityId))
        {
            WorldRange = state.MaxRange;
            ActualRadarRange = state.MaxRange;
            WorldMinRange = 32;
            Offset = Vector2.Zero;
        }
        _coordinates = coordinates;
        _rotation = state.Angle;

        WorldMaxRange = state.MaxRange;

        if (WorldRange > WorldMaxRange)
            WorldRange = WorldMaxRange;

        if (WorldMaxRange < WorldMinRange)
            WorldMinRange = WorldMaxRange;

        ActualRadarRange = Math.Clamp(ActualRadarRange, WorldMinRange, WorldMaxRange);
        _rotateWithEntity = state.RotateWithEntity;

        _radarMarkers.Clear();
        _radarMarkers.AddRange(state.RadarMarkers);
    }

    public void ClearState()
    {
        _coordinates = null;
        _rotation = null;
        _radarMarkers.Clear();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        DrawBacking(handle);

        if (_coordinates == null || _rotation == null)
            return;

        var xformQuery = EntManager.GetEntityQuery<TransformComponent>();
        var fixturesQuery = EntManager.GetEntityQuery<FixturesComponent>();
        var bodyQuery = EntManager.GetEntityQuery<PhysicsComponent>();

        if (!xformQuery.TryGetComponent(_coordinates.Value.EntityId, out var xform) ||
            xform.MapID == MapId.Nullspace)
        {
            return;
        }

        var mapPos = _transform.ToMapCoordinates(_coordinates.Value);
        var viewPosition = FieldNotesMode ? mapPos.Position + Offset : mapPos.Position;
        if (!FieldNotesMode)
            DrawWorldCoordinates(handle, mapPos.Position);
        var ourEntRot = _rotateWithEntity ? _transform.GetWorldRotation(xform) : _rotation.Value;
        var worldToShuttle = GetWorldToShuttle(xform);
        var shuttleToView = GetShuttleToView();

        var ourGridId = xform.GridUid;
        if (FieldNotesMode && EntManager.HasComponent<MapGridComponent>(_coordinates.Value.EntityId))
            ourGridId = _coordinates.Value.EntityId;
        if (EntManager.TryGetComponent<MapGridComponent>(ourGridId, out var ourGrid) &&
            (FieldNotesMode || fixturesQuery.HasComponent(ourGridId.Value)))
        {
            var ourGridToWorld = _transform.GetWorldMatrix(ourGridId.Value);
            var ourGridToShuttle = Matrix3x2.Multiply(ourGridToWorld, worldToShuttle);
            var ourGridToView = ourGridToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(ourGridId.Value, self: true);

            DrawGridSilhouette(handle, ourGridToView, (ourGridId.Value, ourGrid), color);
        }

        var rot = ourEntRot + _rotation.Value;
        var viewBounds = new Box2Rotated(
            new Box2(-WorldRange, -WorldRange, WorldRange, WorldRange).Translated(viewPosition),
            rot,
            viewPosition);
        var viewAABB = viewBounds.CalcBoundingBox();

        _grids.Clear();
        _mapManager.FindGridsIntersecting(
            xform.MapID,
            new Box2(viewPosition - MaxRadarRangeVector, viewPosition + MaxRadarRangeVector),
            ref _grids,
            approx: true,
            includeMap: FieldNotesMode);

        foreach (var grid in _grids)
        {
            var gridUid = grid.Owner;
            if (gridUid == ourGridId ||
                !fixturesQuery.HasComponent(gridUid) ||
                !bodyQuery.TryGetComponent(gridUid, out var gridBody))
            {
                continue;
            }

            EntManager.TryGetComponent<IFFComponent>(gridUid, out var iff);

            if (!_shuttles.CanDraw(gridUid, gridBody, iff))
                continue;

            var gridToWorld = _transform.GetWorldMatrix(gridUid);
            var gridAABB = gridToWorld.TransformBox(grid.Comp.LocalAABB);

            if (!gridAABB.Intersects(viewAABB))
                continue;

            var gridToView = gridToWorld * worldToShuttle * shuttleToView;
            var color = _shuttles.GetIFFColor(grid, self: false, iff);

            DrawGridSilhouette(handle, gridToView, grid, color);
        }

        if (FieldNotesMode)
        {
            DrawAnnotations(handle, worldToShuttle * shuttleToView);
            DrawWorldCoordinates(handle, viewPosition);
        }
        else
            DrawRadarMarkers(handle, worldToShuttle, shuttleToView, mapPos.Position);
    }

    private Matrix3x2 GetWorldToShuttle(TransformComponent xform)
    {
        var center = _coordinates!.Value.Position + (FieldNotesMode ? Offset : Vector2.Zero);
        var posMatrix = Matrix3Helpers.CreateTransform(center, _rotation!.Value);
        var ourEntRot = _rotateWithEntity ? _transform.GetWorldRotation(xform) : _rotation.Value;
        var ourEntMatrix = Matrix3Helpers.CreateTransform(_transform.GetWorldPosition(xform), ourEntRot);
        Matrix3x2.Invert(posMatrix * ourEntMatrix, out var worldToShuttle);
        return worldToShuttle;
    }

    private Matrix3x2 GetShuttleToView()
    {
        var scale = FieldNotesMode && WorldRange > 0
            ? MathF.Max(0, MathF.Min(PixelWidth, PixelHeight) / 2f - MinimapMargin * UIScale) / WorldRange
            : MinimapScale;
        var center = FieldNotesMode ? new Vector2(PixelWidth, PixelHeight) / 2f : MidPointVector;
        return Matrix3x2.CreateScale(new Vector2(scale, -scale)) * Matrix3x2.CreateTranslation(center);
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        var previousOffset = Offset;
        base.MouseMove(args);
        // The table has a fixed square size, whereas handheld maps fill the available window space.
        var radius = MathF.Min(Width, Height) / 2f - MinimapMargin;
        if (FieldNotesMode && radius > 0)
            Offset = previousOffset + (Offset - previousOffset) * (MidPoint / radius);
    }

    private void DrawAnnotations(DrawingHandleScreen handle, Matrix3x2 worldToView)
    {
        for (var i = 0; i < Annotations.Count; i++)
        {
            if (Annotations[i].WorldMap != DisplayedWorldMap)
                continue;

            var point = Vector2.Transform(Annotations[i].WorldPosition, worldToView);
            if (!((UIBox2) PixelSizeBox).Contains(point))
                continue;

            handle.DrawCircle(point, 11 * UIScale, Color.Black);
            handle.DrawCircle(point, 9 * UIScale, i == SelectedAnnotation ? Color.Gold : Color.DarkRed);
            var label = (i + 1).ToString();
            var dimensions = handle.GetDimensions(Font, label, UIScale);
            handle.DrawString(Font, point + new Vector2(-dimensions.X / 2f, dimensions.Y / 2f), label, UIScale, Color.White);
        }
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);
        if (!FieldNotesMode || args.Function != EngineKeyFunctions.UIClick ||
            _coordinates == null || _rotation == null || !((UIBox2) PixelSizeBox).Contains(args.RelativePixelPosition) ||
            !EntManager.TryGetComponent<TransformComponent>(_coordinates.Value.EntityId, out var xform) ||
            xform.MapID == MapId.Nullspace)
        {
            return;
        }

        var worldToView = GetWorldToShuttle(xform) * GetShuttleToView();
        var closest = -1;
        var closestDistance = 16 * UIScale;
        for (var i = 0; i < Annotations.Count; i++)
        {
            if (Annotations[i].WorldMap != DisplayedWorldMap)
                continue;

            var point = Vector2.Transform(Annotations[i].WorldPosition, worldToView);
            if (!((UIBox2) PixelSizeBox).Contains(point))
                continue;

            var distance = Vector2.Distance(args.RelativePixelPosition, point);
            if (distance > closestDistance)
                continue;

            closest = i;
            closestDistance = distance;
        }

        if (closest < 0)
            return;

        OnSelectAnnotation?.Invoke(closest);
        args.Handle();
    }

    private void DrawWorldCoordinates(DrawingHandleScreen handle, Vector2 position)
    {
        var text = Loc.GetString(
            "medieval-cartographer-table-coordinates",
            ("x", position.X.ToString("F0")),
            ("y", position.Y.ToString("F0")));
        var dimensions = handle.GetDimensions(Font, text, 1f);
        const float margin = 8f;
        const float padding = 4f;
        var textPosition = new Vector2(PixelWidth - dimensions.X - margin, margin);
        var background = new UIBox2(
            textPosition - new Vector2(padding),
            textPosition + dimensions + new Vector2(padding));

        handle.DrawRect(background, Color.Black.WithAlpha(0.65f));
        handle.DrawString(Font, textPosition, text, Color.White);
    }

    private void DrawGridSilhouette(
        DrawingHandleScreen handle,
        Matrix3x2 gridToView,
        Entity<MapGridComponent> grid,
        Color color)
    {
        if (FieldNotesMode)
        {
            DrawGeography(handle, gridToView, grid);
            return;
        }

        var gridData = GridData.GetOrNew(grid.Owner);

        if (gridData.LastBuild < grid.Comp.LastTileModifiedTick)
        {
            gridData.Vertices.Clear();

            var tileSize = grid.Comp.TileSize;
            var tiles = Maps.GetAllTilesEnumerator(grid.Owner, grid.Comp);

            while (tiles.MoveNext(out var tileRef))
            {
                var index = tileRef.Value.GridIndices;

                var bl = Maps.TileToVector(grid, index);
                var br = bl + new Vector2(tileSize, 0f);
                var tr = bl + new Vector2(tileSize, tileSize);
                var tl = bl + new Vector2(0f, tileSize);

                gridData.Vertices.Add(bl);
                gridData.Vertices.Add(br);
                gridData.Vertices.Add(tl);

                gridData.Vertices.Add(br);
                gridData.Vertices.Add(tl);
                gridData.Vertices.Add(tr);
            }

            gridData.EdgeIndex = gridData.Vertices.Count;
            gridData.LastBuild = grid.Comp.LastTileModifiedTick;
        }

        var totalData = gridData.Vertices.Count;
        Extensions.EnsureLength(ref _silhouetteVertices, totalData);

        for (var i = 0; i < totalData; i++)
        {
            _silhouetteVertices[i] = Vector2.Transform(gridData.Vertices[i], gridToView);
        }

        const int batchSize = 3 * 4096;

        for (var start = 0; start < totalData; start += batchSize)
        {
            var count = Math.Min(batchSize, totalData - start);
            handle.DrawPrimitives(
                DrawPrimitiveTopology.TriangleList,
                new Span<Vector2>(_silhouetteVertices, start, count),
                color.WithAlpha(SilhouetteAlpha));
        }
    }

    private void DrawGeography(DrawingHandleScreen handle, Matrix3x2 gridToView, Entity<MapGridComponent> grid)
    {
        if (!_geographyData.TryGetValue(grid.Owner, out var data))
        {
            data = new GeographyDrawData();
            _geographyData.Add(grid.Owner, data);
        }

        if (data.LastBuild == null || data.LastBuild < grid.Comp.LastTileModifiedTick)
        {
            data.Vertices.Clear();
            var tiles = Maps.GetAllTilesEnumerator(grid.Owner, grid.Comp);
            var tileSize = grid.Comp.TileSize;
            while (tiles.MoveNext(out var tileRef))
            {
                var color = GetTerrainColor(tileRef.Value.Tile.TypeId);
                if (!data.Vertices.TryGetValue(color, out var vertices))
                {
                    vertices = new List<Vector2>();
                    data.Vertices.Add(color, vertices);
                }

                var bottomLeft = Maps.TileToVector(grid, tileRef.Value.GridIndices);
                var bottomRight = bottomLeft + new Vector2(tileSize, 0);
                var topRight = bottomLeft + new Vector2(tileSize);
                var topLeft = bottomLeft + new Vector2(0, tileSize);
                vertices.Add(bottomLeft);
                vertices.Add(bottomRight);
                vertices.Add(topLeft);
                vertices.Add(bottomRight);
                vertices.Add(topLeft);
                vertices.Add(topRight);
            }
            data.LastBuild = grid.Comp.LastTileModifiedTick;
        }

        const int batchSize = 3 * 4096;
        foreach (var (color, vertices) in data.Vertices)
        {
            Extensions.EnsureLength(ref _silhouetteVertices, vertices.Count);
            for (var i = 0; i < vertices.Count; i++)
                _silhouetteVertices[i] = Vector2.Transform(vertices[i], gridToView);

            for (var start = 0; start < vertices.Count; start += batchSize)
            {
                handle.DrawPrimitives(DrawPrimitiveTopology.TriangleList,
                    new Span<Vector2>(_silhouetteVertices, start, Math.Min(batchSize, vertices.Count - start)), color);
            }
        }
    }

    private Color GetTerrainColor(int typeId)
    {
        if (_terrainColors.TryGetValue(typeId, out var color))
            return color;

        var id = _tileDefinitions[typeId].ID;
        if (id.Contains("Water", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#578CA8");
        else if (id.Contains("Snow", StringComparison.OrdinalIgnoreCase) || id.Contains("Ice", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#D2DEDA");
        else if (id.Contains("Grass", StringComparison.OrdinalIgnoreCase) || id.Contains("Jungle", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#697F50");
        else if (id.Contains("Sand", StringComparison.OrdinalIgnoreCase) || id.Contains("Desert", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#C7B77D");
        else if (id.Contains("Dirt", StringComparison.OrdinalIgnoreCase) || id.Contains("Soil", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#957755");
        else if (id.Contains("Wood", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#BB9165");
        else if (id.Contains("Cave", StringComparison.OrdinalIgnoreCase) || id.Contains("Rock", StringComparison.OrdinalIgnoreCase) ||
                 id.Contains("Basalt", StringComparison.OrdinalIgnoreCase) || id.Contains("Chromite", StringComparison.OrdinalIgnoreCase))
            color = Color.FromHex("#646569");
        else
            color = Color.FromHex("#ADB0A6");

        _terrainColors.Add(typeId, color);
        return color;
    }

    private void DrawRadarMarkers(
        DrawingHandleScreen handle,
        Matrix3x2 worldToShuttle,
        Matrix3x2 shuttleToView,
        Vector2 playerWorldPos)
    {
        if (_radarMarkers.Count == 0)
            return;

        var worldToView = worldToShuttle * shuttleToView;
        var radarRangeSq = ActualRadarRange * ActualRadarRange;

        foreach (var marker in _radarMarkers)
        {
            if (marker.RsiPath is not { } rsiPath || marker.State is not { } rsiState)
                continue;

            var screenPos = Vector2.Transform(marker.Position, worldToView);

            Texture texture = Texture.White;
            var path = new ResPath(rsiPath);
            if (_resCache.TryGetResource<RSIResource>(path, out var rsi))
                texture = rsi.RSI[rsiState].Frame0;

            var sizeVector = new Vector2(marker.ZoomScaling ? marker.Size * MinimapScale : marker.Size, marker.ZoomScaling ? marker.Size * MinimapScale : marker.Size) * texture.Size;
            var topLeft = screenPos - (sizeVector / 2f);

            var drawRect = UIBox2.FromDimensions(topLeft, sizeVector);
            handle.DrawTextureRect(texture, drawRect, marker.Color);
        }
    }
}
