using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Imperial.Medieval.MedievalMap;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Imperial.Medieval.MedievalMap;



[GenerateTypedNameReferences]
public sealed partial class MedievalMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    private readonly SpriteSystem _spriteSystem = default!;
    private string? _texturePath;
    public Action<Vector2, string>? OnAnnotate;


    public MedievalMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entityManager.System<SpriteSystem>();

        var vScrollBar = MapContainer.GetChild(1);
        var hScrollBar = MapContainer.GetChild(2);

        vScrollBar.ModulateSelfOverride = Color.Black;
        hScrollBar.ModulateSelfOverride = Color.Black;
        MapBackground.OnPlaceAnnotation += position => OnAnnotate?.Invoke(position, AnnotationTitle.Text);
        MapBackground.OnSelectAnnotation += SelectAnnotation;
        MapBackground.OnZoom += ZoomMap;
    }

    private void ZoomMap(float delta)
    {
        if (MapBackground.Texture == null) return;

        var minimumScale = (SetSize.X - 40) / MapBackground.Texture.Width;
        var scale = Math.Clamp(MapBackground.TextureScale.X + delta / 10, minimumScale, minimumScale * 8);
        MapBackground.TextureScale = new Vector2(scale);
        MapBackground.SetSize = MapBackground.TextureScale * MapBackground.Texture.Size;
    }

    #region Public API

    public void UpdateBackground(string path)
    {
        if (_texturePath == path) return;
        _texturePath = path;
        var texture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new(path)));

        MapBackground.Texture = texture;
        MapBackground.TextureScale = (SetSize - new Vector2(40)) / texture.Size;
        MapBackground.SetSize = MapBackground.TextureScale * texture.Size;
    }

    public void UpdateAnnotations(MedievalMapBoundUiState state, bool canAnnotate)
    {
        MapBackground.Annotations = state.Annotations;
        MapBackground.CanAnnotate = canAnnotate;
        AnnotationEditor.Visible = canAnnotate;
        SurveyDescription.SetMessage(canAnnotate ? state.PendingDescription : Loc.GetString("book-cartography-read-hint"));
        AnnotationList.DisposeAllChildren();
        for (var i = 0; i < state.Annotations.Count; i++)
        {
            var index = i;
            var annotation = state.Annotations[i];
            var button = new Button
            {
                Text = $"{i + 1}. {annotation.Title}",
                ClipText = true,
                ToolTip = annotation.Description,
                HorizontalExpand = true
            };
            button.OnPressed += _ => SelectAnnotation(index);
            AnnotationList.AddChild(button);
        }

        if (!canAnnotate)
            AnnotationTitle.Text = "";
    }

    private void SelectAnnotation(int index)
    {
        if (index < 0 || index >= MapBackground.Annotations.Count) return;
        MapBackground.SelectedAnnotation = index;
        SurveyDescription.SetMessage(MapBackground.Annotations[index].Description);
    }

    #endregion
}
